package Models;

public enum CATEGORIAS_VAGAO {
    VAGAO_DE_PASSAGEIROS_COMUM,
    VAGAO_LEITO,
    VAGAO_RESTAURANTE,
    VAGAO_DE_PRIMEIRA_CLASSE,
    VAGAO_PANORAMICO,
    VAGAO_SANITARIO,
    VAGAO_DE_COMANDO,
    VAGAO_PLATAFORMA,
    VAGAO_TANQUE,
    VAGAO_FECHADO,
    VAGAO_GONDOLA,
    VAGAO_HOPPER,
    VAGAO_PRANCHA,
    VAGAO_BAU_REFRIGERADO,
    VAGAO_PORTA_AUTOMOVEIS,
    VAGAO_DE_TORAS,
    VAGAO_BETONEIRA
}
